# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        app_db_provider:
            entity:
                class: AppBundle:User

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: (^/$|^/login/error$)
            anonymous: true

        secure:
            pattern: ^/.*
            anonymous: false
            provider: app_db_provider
            trusted_sso:
                manager: cas_sso
                login_path: /
                login_action: false # BeSimpleSsoAuthBundle:TrustedSso:login
                logout_action: false # BeSimpleSsoAuthBundle:TrustedSso:logout
                create_users: true
                created_users_roles: [ROLE_USER]
                check_path: /login/check
                failure_path: /login/error
            logout:
                path: /logout
                target: /

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
