# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    doctrine.orm.security.user.provider.class: AppBundle\Security\User\EntityUserProvider
    be_simple.sso_auth.client.option.curlopt_sslversion.value: 0

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
